#Home Network Setup

CIRCUITPY_WIFI_SSID="Clan Tacon"
CIRCUITPY_WIFI_PASSWORD="CL4n.TaC0n.3419"
CIRCUITPY_WEB_API_PASSWORD="Pic0W_Serv3r"

#Office Network Setup

CIRCUITPY_WIFI_SSID2="Clan Tacon"
CIRCUITPY_WIFI_PASSWORD2="CL4n.TaC0n.3419"
CIRCUITPY_WEB_API_PASSWORD2="Pic0W_Serv3r_OfF1ce"

CIRCUITPY_WEB_API_PORT=80