#Home Network Setup

CIRCUITPY_WIFI_SSID="WifiNetwork"
CIRCUITPY_WIFI_PASSWORD="Apassw0rd123"
CIRCUITPY_WEB_API_PASSWORD="Pic0W_Serv3r"

#Office Network Setup

CIRCUITPY_WIFI_SSID2="Another Wifi Netowrk"
CIRCUITPY_WIFI_PASSWORD2="ItsJust4T3st."
CIRCUITPY_WEB_API_PASSWORD2="Pic0W_Serv3r_OfF1ce"

CIRCUITPY_WEB_API_PORT=80
